spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 715350382641274
            client-secret: 12d54762d8dd6260a48dfa90da57b867
           
          google:
            client-id: 268689523809-fpatr3ei1deb1d0e5ffn3880ha86ml97.apps.googleusercontent.com
            client-secret: HYJM_nlx8d_GtjnroxCEkKJp 
        provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)      
